---
- name: arp table on unix localhost
  hosts: islocal
  gather_facts: no
  tasks:
  - raw: "arp -a"
    register: show
  - debug: var=vars

- name: arp table on Cisco IOS router.
  hosts:  ciscoios
  gather_facts: no
  tasks:
  - raw: "show ip arp vrf management"
    register: show
  - debug: var=vars
